version: '3.9'
services:
  deltachat-build:
    build:
      context: .
      dockerfile: ./Docker/build-agent/Dockerfile
  deltachat-test:
    build:
      context: .
      dockerfile: ./Docker/test-agent/Dockerfile
    depends_on:
      - deltachat-build
